import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { join } from 'node:path';

const require = createRequire(import.meta.url);
const fontDir = join(require.resolve('@fontsource/inter/package.json'), '..', 'files');

const encode = async (weight: number) => (await readFile(join(fontDir, `inter-latin-${weight}-normal.woff`))).toString('base64');

const body = `// Generated by pnpm fonts:embed from @fontsource/inter (SIL Open Font License 1.1; see fonts/LICENSE-Inter.txt).
const decode = (b64: string): ArrayBuffer => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0)).buffer;

export const INTER_400 = decode('${await encode(400)}');
export const INTER_700 = decode('${await encode(700)}');
`;
await writeFile(join(import.meta.dirname, '..', 'worker', 'fonts.ts'), body);
console.log('wrote worker/fonts.ts');
