import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { USER_AGENT } from '@ccip-dev/core';

export const DOCS_BASE = 'https://raw.githubusercontent.com/smartcontractkit/documentation/main/src/config/data/ccip/v1_2_0/mainnet';
/** USD stablecoins among fee-token symbols, including a chain's USD gas token (xDAI on Gnosis, GHO on Lens, USDT0 and gUSDT on Stable). */
export const STABLE_SYMBOLS: ReadonlySet<string> = new Set(['GHO', 'WGHO', 'pathUSD', 'USDC', 'USDT', 'USDT0', 'WUSDT0', 'WgUSDT', 'USD1', 'WXDAI']);
/** Symbols that are neither a gas token nor a USD stablecoin; they stay out of the table and count as other. */
export const UNGROUPED_SYMBOLS: ReadonlySet<string> = new Set();

const OUT = path.resolve(import.meta.dirname, '../../packages/core/src/fee-groups-docs.ts');

export interface DocsChain {
  chainSelector: string;
  feeTokens?: string[];
}
export interface DocsToken {
  tokenAddress: string;
}
export type DocsChains = Record<string, DocsChain>;
export type DocsTokens = Record<string, Record<string, DocsToken>>;
export interface GroupRules {
  stable: ReadonlySet<string>;
  ungrouped: ReadonlySet<string>;
}
export interface GroupEntry {
  key: string;
  chain: string;
  group: 'native' | 'stable';
  symbol: string;
}

const compare = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

/** EVM addresses and the 64-hex ids of Aptos and Sui are case-insensitive, and the CCIP API reports them lowercase. */
export function docsAddress(address: string): string {
  return /^0x[0-9a-fA-F]+$/.test(address) ? address.toLowerCase() : address;
}

export function groupFeeTokens(
  chains: DocsChains,
  tokens: DocsTokens,
  rules: GroupRules = { stable: STABLE_SYMBOLS, ungrouped: UNGROUPED_SYMBOLS },
): { entries: GroupEntry[]; review: string[] } {
  const entries: GroupEntry[] = [];
  const symbolAt = new Map<string, string>();
  const leftOut = new Map<string, string[]>();
  const missing: string[] = [];
  let linkChains = 0;
  for (const [chain, info] of Object.entries(chains).sort(([a], [b]) => compare(a, b))) {
    for (const symbol of info.feeTokens ?? []) {
      if (symbol === 'LINK') {
        linkChains += 1;
        continue;
      }
      if (rules.ungrouped.has(symbol)) {
        leftOut.set(symbol, [...(leftOut.get(symbol) ?? []), chain]);
        continue;
      }
      const token = tokens[symbol]?.[chain];
      if (!token) {
        missing.push(`missing ${symbol} on ${chain}: tokens.json has no address for it; hand-add it in fee-groups.ts if it is a real fee token`);
        continue;
      }
      const key = `${info.chainSelector}:${docsAddress(token.tokenAddress)}`;
      const earlier = symbolAt.get(key);
      if (earlier !== undefined) throw new Error(`${key} is listed as both ${earlier} and ${symbol}`);
      symbolAt.set(key, symbol);
      entries.push({ key, chain, group: rules.stable.has(symbol) ? 'stable' : 'native', symbol });
    }
  }
  const bySymbol = new Map<string, GroupEntry[]>();
  for (const e of entries) bySymbol.set(e.symbol, [...(bySymbol.get(e.symbol) ?? []), e]);
  const grouped = [...bySymbol.values()]
    .sort((a, b) => compare(a[0]!.group, b[0]!.group) || compare(a[0]!.symbol, b[0]!.symbol))
    .map((list) => `${list[0]!.group} ${list[0]!.symbol}: ${list.map((e) => e.chain).join(', ')}`);
  const ungrouped = [...leftOut.entries()].sort(([a], [b]) => compare(a, b)).map(([symbol, list]) => `left out ${symbol}: ${list.join(', ')}`);
  return { entries, review: [...grouped, ...ungrouped, `skipped LINK on ${linkChains} chains`, ...missing] };
}

export function renderGroupsFile(entries: readonly GroupEntry[]): string {
  return [
    "// Generated by `pnpm fee-groups:generate` from the CCIP docs' mainnet chains.json (fee-token symbols) and tokens.json",
    '// (addresses). Regenerate instead of editing; fee tokens the docs miss are hand-added in fee-groups.ts.',
    "export const FEE_TOKEN_GROUPS_FROM_DOCS: Readonly<Record<string, { group: 'native' | 'stable'; symbol: string }>> = {",
    ...entries.map((e) => `  ${JSON.stringify(e.key)}: { group: ${JSON.stringify(e.group)}, symbol: ${JSON.stringify(e.symbol)} }, // ${e.chain}`),
    '};',
    '',
  ].join('\n');
}

async function fetchDocs<T>(name: string): Promise<T> {
  const res = await fetch(`${DOCS_BASE}/${name}`, { headers: { 'user-agent': USER_AGENT }, signal: AbortSignal.timeout(30_000) });
  if (!res.ok) throw new Error(`${DOCS_BASE}/${name}: HTTP ${res.status}`);
  return (await res.json()) as T;
}

async function main(): Promise<void> {
  const [chains, tokens] = await Promise.all([fetchDocs<DocsChains>('chains.json'), fetchDocs<DocsTokens>('tokens.json')]);
  const { entries, review } = groupFeeTokens(chains, tokens);
  await writeFile(OUT, renderGroupsFile(entries));
  console.log(`wrote ${entries.length} fee tokens to ${path.relative(process.cwd(), OUT)}; check each line:`);
  for (const line of review) console.log(line);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
